spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/doctor_appointment}
server.port=${PORT:8080}


jwt.secret=doctorSecretKey
jwt.expiration=3600000


# Email Configuration
# INSTRUCTIONS:
# 1. Enter your Gmail address below.
# 2. Generate an App Password (NOT your login password) at: https://myaccount.google.com/apppasswords
# 3. Paste the 16-character App Password below.
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=doctorappointment26@gmail.com
spring.mail.password=1234567890

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Razorpay Config
razorpay.key_id=${RAZORPAY_KEY_ID:rzp_test_YOUR_ID_HERE}
razorpay.key_secret=${RAZORPAY_KEY_SECRET:YOUR_SECRET_HERE}
